### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lukemelia** [j-mcnally/cordova-statusTap#1]
Looks useful. Thanks for putting it together. What OSS license are you making this available under? I'd suggest MIT or BSD, if you're taking requests. :)

**Comment by j-mcnally** [comment]
yeah i dont really care, this is totally open which works better / is more open MIT or BSD im not a lawyer. I'd just like people to contribute improvements back so that others can use them, but they can use it in any commercial work without attribution.

**Comment by lukemelia** [comment]
Sounds good @1fb5cbbf8af67ecabeb9a6074b820fa7d0c6fdb4
