### ISSUE TITLE
Should adjust location of tap area when phone is rotated

### ISSUE THREAD

**Issue by lukemelia** [j-mcnally/cordova-statusTap#2]

**Comment by j-mcnally** [comment]
i will try to get an update pushed. this was more of a starting point for the opensource community. but if i find some time ill try to add this functionality.

**Comment by kevshub** [comment]
Has this been added because it is turning when the phone is rotated it does seem to move, however if the phone is locked in portrait only it still seems to turn regardless - what line needs taking out to stop this happening?

**Comment by j-mcnally** [comment]
fed153c3ffaba3d28e3c349304fea69e43015420 fixes this issue
