### ISSUE TITLE
Cordova/PhoneGap 3.0 support?

### ISSUE THREAD

**Issue by gregsramblings** [j-mcnally/cordova-statusTap#8]
Any plans to update this to the 3.0 plugin architecture?

**Comment by gregsramblings** [comment]
Andy Trice just forked and updated to the Cordova/PhoneGap 3.x interface -- 

http://www.tricedesigns.com/2013/10/08/status-tapscroll-to-top-in-phonegap-apps-on-ios/

https://github.com/triceam/cordova-statusTap

Greg

**Comment by j-mcnally** [comment]
nice, glad to see some people working on / with it.

Thanks for sharing.
